import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import "./globals.css";
import theme from "./theme";
import { cn } from "~/utils/helpers";
import TanstackQueryProvider from "~/providers/tanstack-query";
import Toast from "~/components/toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "45Group",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "scroll-smooth min-h-screen")}>
        <AppRouterCacheProvider>
          <TanstackQueryProvider>
            <ThemeProvider theme={theme}>
              <Toast />
              {children}
            </ThemeProvider>
          </TanstackQueryProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
