import type { Metadata } from "next";
import { ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import "./globals.css";
import theme from "./theme";
import { cn } from "~/utils/helpers";
import TanstackQueryProvider from "~/providers/tanstack-query";
import Toast from "~/components/toast";
import { dancing_script, merriweather } from "~/utils/fonts";
import AppProgressBar from "~/components/app-progress-bar";

export const metadata: Metadata = {
  title: "45Group",
  description: "Generated by create next app",
  keywords: ["Hotel 45", "Hotel45", "Event 45", "Club 45", "Lounge 45", "Bar 45", "Bar 90"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(dancing_script.variable, merriweather.variable, "min-h-screen scroll-smooth")}
      >
        <AppRouterCacheProvider>
          <TanstackQueryProvider>
            <ThemeProvider theme={theme}>
              <Toast />
              <AppProgressBar />
              {children}
            </ThemeProvider>
          </TanstackQueryProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
