name: CI for Staging

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Log NODE_ENV
        run: echo "NODE_ENV is $NODE_ENV"

      - name: Install dependencies
        run: yarn install

      - name: Run lint-staged
        run: yarn lint-staged

      - name: Build project
        run: yarn build

      - name: Mirgate DB
        run: yarn migrate
